### ISSUE TITLE
Remove Red Hat from the OpenADx website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/openadx.eclipse.org#127]
Red Hat is no longer part of the OpenADx working group. Please remove the logo from the website https://openadx.eclipse.org/members/
Thanks,
Zahra

**Comment by autumnfound** [comment]
@ZahraFazli does this impact the presence of documents by/from Red Hat on the resources page? Should we remove them as well?

**Comment by ariexi** [comment]
> 
> 
> @ZahraFazli does this impact the presence of documents by/from Red Hat on the resources page? Should we remove them as well?

@autumnfound let me try .... ;-)
The articles from Red Hat are general and not OpenADx specific. If would like to keep them because they are also valid for OpenADx and we do not want to reinvent the wheel.
And I am sure, Red Hat will (sooner or later) be part of OpenADx again, if times will better ... ;-)
