### ISSUE TITLE
Implement openadx look and feel

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openadx.eclipse.org#13]
Stephanie created the following files for the look and feel for openADx website:

[background_innerpage.zip](https://github.com/EclipseFdn/openadx.eclipse.org/files/3297463/background_innerpage.zip)
[background_openadx.zip](https://github.com/EclipseFdn/openadx.eclipse.org/files/3297465/background_openadx.zip)
![Innerpage](https://user-images.githubusercontent.com/893942/59612735-9f8c5800-90eb-11e9-8736-3ec40b7c073b.png)
![openadx (1)](https://user-images.githubusercontent.com/893942/59612736-9f8c5800-90eb-11e9-9be7-ab1ceb1e8073.png)
[OpenADx_logo.zip](https://github.com/EclipseFdn/openadx.eclipse.org/files/3297466/OpenADx_logo.zip)
![subpage](https://user-images.githubusercontent.com/893942/59612737-9f8c5800-90eb-11e9-8773-42b10a2e6f4a.png)

**Comment by ariexi** [comment]
Looks really great!

**Comment by ericpoirier** [comment]
Here is the link of the staging website:

https://eclipsefdn.github.io/openadx.eclipse.org/

Please let me know if there's anything to be changed.

Thanks.

**Comment by ariexi** [comment]
Can we fill (instead of lorem ipsum) the "Vision" on the home page [https://eclipsefdn.github.io/openadx.eclipse.org/](https://eclipsefdn.github.io/openadx.eclipse.org/) with the following content?


Autonomous driving (AD) is an extremely complex challenge with a complex development process, which is slowed at every turn by incompatibility between widely used development tools. The tools we already use in and of themselves are very good, but they do not work seamlessly with one another simply because they were never designed to work with each other. This is an industry-wide issue. It slows us all down in the race to automated driving. It costs money and precious resources to reduce the problem to a manageable level. And the thing about it is that the tool chain itself is not something we can monetize.

**Comment by ariexi** [comment]
Can we fill (instead of lorem ipsum) the "Working Group" on the home page https://eclipsefdn.github.io/openadx.eclipse.org/ with the following content?

The OpenADx working group will coordinate the development of Eclipse Foundation projects on the following topics:
- Implementation of interfaces between the development steps
- Implementation of common standards from other working groups (e.g. VDA Leitinitiative)
- Definition of an initial setup for fast implementation
- Ensures interoperability between development stages

Find out how to join, how to participate and contribute

**Comment by ariexi** [comment]
Can we fill (instead of lorem ipsum) the "Technologies" on the home page https://eclipsefdn.github.io/openadx.eclipse.org/ with the following content?


Automated Driving (AD) is clustered into three equally important technology areas:
- In-vehicle technology
- Cloud technology (backend)
- Design, development, test and validation tools (tool chain)

OpenADx is currently focused on the AD tool chain. The goal is to accelerate AD development through open collaboration and open source.
OpenADx’ vision is to ensure transparency and make the complex AD tool landscape more easily accessible for enterprise users.

**Comment by ariexi** [comment]
Can we fill (instead of lorem ipsum) the "Resources" on the home page https://eclipsefdn.github.io/openadx.eclipse.org/ with the following content?

Explore our information material about OpenADx and Autonomous Driving.

**Comment by ariexi** [comment]
I guess, the links in the "Learn more" buttons will be updated after launch, right?

**Comment by ericpoirier** [comment]
Hi,

I updated the content of the home page and I also updated the links to go to their respective section.

Let me know if there's anything else for the home page.

Thanks.

**Comment by chrisguindon** [comment]
Thank you @ericpoirier 

The website is now live: https://openadx.eclipse.org/index.html

Please let us know if there is any other changes required for the official launch!
