### ISSUE TITLE
Migrate website source repository to Eclipse Gitlab

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openadx.eclipse.org#157]
Over the last few months, we've been busy migrating some of our websites to Eclipse Gitlab:
https://gitlab.eclipse.org/eclipsefdn/it/websites

Today, I would like to recommend that we migrate this website repository under https://gitlab.eclipse.org/eclipsefdn/it/websites

This move makes it easier for foundation staff to collaborate and manage priorities since we can review issues by group https://gitlab.eclipse.org/groups/eclipsefdn/it/websites/-/issues

Triage is a bit more time-consuming on Github since we need to manually visit the issue queue of each project.

@ariexi Do you have any issues with us moving this repository? Also, if you agree, do you need some time to communicate this change with the WG before we do the move?

Thanks!

**Comment by ariexi** [comment]
Hi @chrisguindon,
thanks for your information!
I am sure, the move will not affect the website itself, right?

I fully agree to the move, because:
- that will also solve some "history" problems I have with GitHub right now
- it will help me to jump into GitLab

I don´t think, that I need time to communicate to my WG, because in very rare cases other will edit the site. ;-)

Looking forward and thank you!

Please let me know, when you have moved ... ;-)

Best,
Andy

**Comment by chrisguindon** [comment]
The website will not be affected. Everything should continue to work as before. The only change will be that we will now use Eclipse Gitlab instead of Github to collaborate on this project!

**Comment by chrisguindon** [comment]
Thanks @ariexi!

Now that https://github.com/EclipseFdn/openadx.eclipse.org/pull/158 is merged, I am going to start the migration! I will let you know once it's all done!

**Comment by chrisguindon** [comment]
@ariexi The move has been done!
https://gitlab.eclipse.org/eclipsefdn/it/websites/openadx.eclipse.org

Feel free to open issues here now: https://gitlab.eclipse.org/eclipsefdn/it/websites/openadx.eclipse.org/-/issues
